project:
  type: book
  output-dir: docs

book:
  title: "Mass Spec Academy"
  favicon: figs/favicon.png
  page-navigation: true
  image: figs/ExtendedGeometryLineDrawing.svg
  output-file: "Mass Spectrometry Book"
  site-url: https://noahmclean.github.io/quartoSandbox/
  chapters: 
    - index.qmd
    - part: "Background"
      href: overview.qmd
      chapters: 
      - text: "Concept Review"
        href: background.qmd
      - ion_sources.qmd
    - part: "Analytical Considerations"
      chapters: 
      - baselines.qmd
      - peak_tails_abundance_sensitivity.qmd
    - part: "Isotope Systems"
      chapters:
      - U_Pb.qmd
    - part: "Interpreting Data"
      chapters:
      - basic_stats_refresher.qmd
  navbar:
    logo: figs/logo3_250.jpg
    right:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/noahmclean/quartoSandbox
          - text: Suggest an edit
            href:  https://github.com/noahmclean/quartoSandbox/issues/new


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 3
    toc-title: "Contents"
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^https:\/\/noahmclean\.github\.io.*$'
    code-fold: true
  pdf: default

number-depth: 3