---
title: "Overview"
listing:
  id: overview-listing
  contents:
    - background.qmd
    - ion_sources.qmd
  type: default
  sort: false
  sort-ui: false
  filter-ui: false
  fields: [title, image]
---

## What is a Mass Spectrometer?

A mass spectrometer separates atoms by their atomic mass. Scientists have long known how to separate different elements based on their chemical properties. Thousands of years ago, metallic copper was first smelted from copper ore, giving rise to the [Copper Age](https://en.wikipedia.org/wiki/Chalcolithic). Modern geochemical labs efficiently separate even very chemically similar elements, such as the rare earth elements, via techniques like anion exchange chromatography. These techniques separate one element from another, like separating samarium (Sm) from neodymium (Nd). 

Recall that the number of protons in an atom determines the number of electrons that are needed to balance their charge. The number of electrons in an atom determines its chemical behavior —- whether and how it makes chemical bonds with other atoms. But the nucleus of an atom doesn’t just contain protons, it also contains neutrons. Atoms with the same number of protons but different numbers of neutrons are called isotopes. Different isotopes of the same element behave in a chemically similar manner: you can make CO$_{2}$ with $^{12}$C, $^{13}$C, or $^{14}$C. 

The relative abundances of the isotopes of an element are key to a broad array of geological processes, including the radioactivity used as a clock in geochronology, geochemical processes that fractionate radioactive parent isotopes from their radiogenic daughter products, and temperature- and environment-dependent kinetic reaction rates. To separate isotopes by their atomic mass, we need a mass spectrometer.

Separating atoms by their atomic mass is usually accomplished by first ionizing the atoms, for instance by stripping an electron off to create an ion with a $+1$ positive charge. The ions can then be separated according to their mass-to-charge ratio, often denoted $m/z$, using electric and magnetic fields.

## Background Contents

::: {#overview-listing}
:::